### ISSUE TITLE
Pyodbc SQL Server Driver Connection String

### ISSUE THREAD

**Issue by denvaar** [ODM2/ODM2PythonAPI#26] opened 2016-01-20 23:42 UTC
@AmberSJones and I have been running into some issues when connecting to a SQL Server database from a windows machine. The driver portion of the connection string (`SQL+Server+Native+Client+10.0`) does not always match the name of the driver on each machine. 

For example, my machine only had drivers named `SQL+Server` and `ODBC+Driver+11+for+SQL+Server`. The names of the drivers will not always be exactly the same. I have some code that can grab the names of the user's installed drivers. I am going to add that to ODMconnection.py so that it inserts the appropriate name into the connection sting.

**Comment by denvaar** [comment] 2016-01-22 22:49
Marking as "ready for testing" for now. Will close after we are sure it's working correctly.

**Comment by lsetiawan** [comment] 2018-01-16 22:06
Seems like this was addressed by https://github.com/ODM2/ODM2PythonAPI/commit/83faa0abb1ac3fa0778a64ab1dc28596a13949a8, @emiliom could you please confirm and then close this issue? Thanks.

**Comment by emiliom** [comment] 2019-04-21 06:18
I'm not in a position to test MS SQL Server connectivity, and few people (if any) are using or testing ODM2 with SQL Server. Looks like https://github.com/ODM2/ODM2PythonAPI/commit/83faa0abb1ac3fa0778a64ab1dc28596a13949a8 (in its changes to [odm2api/ODMconnection.py](https://github.com/ODM2/ODM2PythonAPI/blob/master/odm2api/ODMconnection.py)) was intended to address the original issue, but that was a long time ago, and the changes from that commit have themselves already changed (the current code looks more hard-wired than the code introduced in that commit ...). So, closing this issue as likely already addressed, and too old in any case.

**Closed by emiliom** 2019-04-21 06:18 UTC
Labels: bug, ready for testing
